import{a as p,S as L,i as c}from"./assets/vendor-5401a4b0.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const y of r.addedNodes)y.tagName==="LINK"&&y.rel==="modulepreload"&&n(y)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();async function g(s,o){return p.defaults.baseURL="https://pixabay.com",p.get("/api/",{params:{key:"42449001-9f730a509ed4c563c5fe29690",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:30}})}const S=document.querySelector(".form"),u=document.querySelector(".gallery");document.querySelector(".gallery-box");const i=document.querySelector(".loader-top"),m=document.querySelector(".loader-bottom");document.querySelector("input");const a=document.querySelector(".load-image");let d,l,f,h=15;const b=new L(".gallery a",{nav:!0,captionDelay:250,captionsData:"alt",close:!0,enableKeyboard:!0,docClose:!0});S.addEventListener("submit",x);a.addEventListener("click",q);async function x(s){if(s.preventDefault(),i.style.display="block",a.style.display="none",l=1,d=s.target.elements.search.value.trim(),!d){u.innerHTML="",c.info({position:"topRight",message:"Error enter any symbols"}),i.style.display="none";return}try{const{data:{hits:o,totalHits:t}}=await g(d,l);o.length>0?(i.style.display="none",u.innerHTML=v(o),b.refresh(),c.success({position:"topRight",message:`We found ${t} photos`}),a.style.display="block"):(u.innerHTML="",c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"})),t<=h&&(a.style.display="none")}catch{console.log("Error")}finally{i.style.display="none",s.target.reset()}}function v(s=[]){return s.reduce((o,t)=>o+`<li class="gallery-item">
        <a href=${t.largeImageURL}>
          <img class="gallery-img" src ='${t.webformatURL}' alt='${t.tags}'/>
        </a>
        <div class="gallery-text-box">
          <p>Likes: <span class="text-value">${t.likes}</span></p>
          <p>views: <span class="text-value">${t.views}</span></p>
          <p>comments: <span class="text-value">${t.comments}</span></p>
          <p>downloads: <span class="text-value">${t.downloads}</span></p>
      </div>
      </li>`,"")}async function q(s){m.style.display="block",a.style.display="none";const t=document.querySelector(".gallery-item:first-child").getBoundingClientRect().height;try{l+=1;const{data:{hits:n,totalHits:e}}=await g(d,l);if(f=Math.ceil(e/h),a.style.display="block",u.insertAdjacentHTML("beforeend",v(n)),b.refresh(),l===f)return a.style.display="none",c.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(n){console.log(n)}finally{m.style.display="none",window.scrollBy({top:2*t,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
